In [ ]:
import numpy a
s np
np.__version__

'1.23.5'

### 실습1

In [134]:
import numpy as np
arr = np.zeros((5,5))
for i in range(5):
    if i % 5 == 0 or i % 5 == 4:
        arr[i] = 1
    for j in range(5):
        if j % 5 == 0 or j % 5 == 4:
            arr[i][j] = 1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [143]:
import numpy as np
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [144]:
import numpy as np
arr = np.ones((5,5))
for i in range(5):
    if i % 5 == 0 or i % 5 == 4:
        arr[i] = 0
    for j in range(5):
        if j % 5 == 0 or j % 5 == 4:
            arr[i][j] = 0
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [147]:
import numpy as np
arr = np.ones((3,3))
arr = np.pad(arr, pad_width = 1, mode = 'constant', constant_values = 0)
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 실습2

In [137]:
import numpy as np
arr = np.zeros((8,8))
for i in range(8):
    if i % 2 == 1:
        for j in range(8):
            if j % 2 ==0:
                arr[i][j] = 1
    else:
        for j in range(8):
            if j % 2 ==1:
                arr[i][j] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [148]:
import numpy as np
arr = np.ones((8,8))
arr[1::2,1::2] = 0
arr[::2,::2] = 0
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 실습3

In [150]:
import numpy as np
arr = np.array([180,72,172,66,162,60,167,53,176,80,155,60,177,77,130,40])
arr.resize(2,4,2)
arr

array([[[180,  72],
        [172,  66],
        [162,  60],
        [167,  53]],

       [[176,  80],
        [155,  60],
        [177,  77],
        [130,  40]]])